fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

app:
    resource: "@AppBundle/Controller"
    type: annotation
    prefix: /
